name: expense_tracker_app
description: Expense Tracker App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.15.0
  provider: ^6.0.5
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9